<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>changed</key>
	<dict>
		<key>repository.block.patterns</key>
		<array>
			<dict>
				<key>include</key>
				<string>#separator</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#heading</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#blockquote</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#lists</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#raw_block</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#fenced_block</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#link-def</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#html</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#paragraph</string>
			</dict>
		</array>
		<key>repository.block.repository.fenced_block</key>
		<dict>
			<key>begin</key>
			<string>(^|\G)```</string>
			<key>end</key>
			<string>(^|\G)```</string>
			<key>name</key>
			<string>markup.raw.block.markdown</string>
		</dict>
		<key>repository.inline.repository.cite-ref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.begin.markdown</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.other.link.title.markdown</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.other.reference.link.markdown</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.constant.end.markdown</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\[)([^\]]*((@[^[\] ]+)[^\]]*)+)(\])</string>
			<key>name</key>
			<string>meta.cite.reference.markdown</string>
		</dict>
	</dict>
	<key>isDelta</key>
	<true/>
	<key>uuid</key>
	<string>0A1D9874-B448-11D9-BD50-000D93B6E43C</string>
</dict>
</plist>
